### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by muan** [katydecorah/instagram-rss-action#22]
Hi Katy! I've been exploring the actions you've wrote. Thank you for sharing them! However, I gave this one a go, and immediately ran into this issue:

> If you see this error: `TypeError: Cannot read property 'user' of undefined`. Either the Instagram account you entered is invalid or Instragram is ratelimiting your request. If the latter, try reducing your schedule to once or twice a day.

1. it happened the first time I ran this, 2. I double checked the account names they all seem to be correct,

and I see that it seems to be failing on this repository as well:

https://github.com/katydecorah/instagram-rss-action/actions/runs/2678247017

The last updated time to `instagram.json` was 8 month ago and the error persisted through the rewrite (#4).

---

I tried to investigate this locally but it seems to work. I am guessing perhaps the rate limit is limited to GitHub Action containers? Are you observing similar behavior? Is this perhaps expected to not work now?

**Comment by katydecorah** [comment]
Hey @muan! Thanks for trying out the project. You are exactly right about the rate limiting. When I first built this project I hit rate limits every now and then, but it has gotten worse and worse. I suppose it's unsurprising, but disappointing.

I think it's time to archive this repo 🥀

**Comment by muan** [comment]
🥲 Bummer. I may keep a feed generating locally still with the script regardless. Thank you!
